### ISSUE TITLE
Zero downtime deploys

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/feature-requests#1]
Anytime a docker image is updated, restart running containers with zero downtime.

Something like this https://github.com/docker/compose/issues/734#issuecomment-167392770

**Comment by mrrobot47** [comment]
Currently, EasyEngine uses container migrations to update the containers. Container migration is run only when the newer version of EasyEngine has some updates related to docker images. The approach in container migrations is as follows:

1. Pull the required new image, so that starting it does not have the latency of pulling it.
2. Update the `docker-compose.yml` file.
3. Stop and remove the existing container.
4. Start the new container according to the changes in `docker-compose.yml`.

#### Approach for implementing and testing zero downtime updates in EasyEngine:

1. Pull the required new image, so that starting it does not have the latency of pulling it.
2. Use `--project-name=update-ee-version-no-sitename` and scale up the existing containers. Thus, there are two copies now.
3. Remove existing containers site's default contianers. Now, `update-ee-version-no-sitename` deployed containers are handling requests.
4. Update the `docker-compose.yml` file.
5. Start the new default container according to the changes in `docker-compose.yml`.
6. Stop and remove the `update-ee-version-no-sitename` containers. And the state of the site is restored to it's original scale.

#### Possible Test scenarios:

1. Test this with `global-db` container update and hit non-cached pages during the entire process to see the results.
2. Test this with redis container and see if after switching to `update-ee-version-no-sitename` the cache is being hit or not.
3. Test with `nginx-proxy` image itself and see if it is load balancing the other containers as well handling requests properly or not once it is itself scaled.
4. Test about what happens to PHP sessions during switching and updating PHP container.
